#!/bin/bash

chunkc=/Users/laurenzi/code/bin/chunkc
spaces=/Users/laurenzi/code/bin/DisplaySpaces
khd=/Users/laurenzi/code/bin/khd

#sleep 1.00
desktop_mode=$($chunkc tiling::query -d mode)
#currwin=$($chunkc tiling::query --window tag)
currwin=$(sh ./scripts/activeWindow.sh)
khd_mode=$($khd -e "print mode")
float=$($chunkc tiling::query --window float)
spacesout=$($spaces)

echo "$desktop_mode@$khd_mode@$float@${spacesout: -1}@${spacesout: -3:1}@$currwin"
